# Generated by Django 3.2.10 on 2022-06-14 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Visible_status', models.CharField(choices=[('Отображать', 'Отображать'), ('Не отображать', 'Не отображать')], default='Не отображать', max_length=50, verbose_name='Блок на главной')),
            ],
            options={
                'verbose_name': 'Ярлыки',
                'verbose_name_plural': 'Ярлыки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('Image', models.ImageField(upload_to='product/', verbose_name='Изображение')),
                ('Recommendation', models.CharField(choices=[('Отображать', 'Отображать'), ('Не отображать', 'Не отображать')], default='Не отображать', max_length=50, verbose_name='Рекомендации')),
                ('Price', models.IntegerField(verbose_name='Цена')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category', verbose_name='Категория')),
                ('Tags', models.ManyToManyField(blank=True, to='web.Tag', verbose_name='Ярлыки')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
            },
        ),
    ]
