# Generated by Django 3.2.10 on 2022-06-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Color',
            field=models.ImageField(default=0, upload_to='', verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
