# Generated by Django 3.2.10 on 2022-06-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Color',
            field=models.CharField(max_length=50, verbose_name='Цвет'),
        ),
    ]
