# Generated by Django 3.2.10 on 2022-06-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_category_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='Название')),
                ('Image', models.ImageField(upload_to='category/', verbose_name='Изображение')),
                ('Color', models.CharField(max_length=50, verbose_name='Цвет (html color code)')),
                ('About', models.TextField(blank=True, verbose_name='Описание')),
                ('Date', models.DateField(blank=True, verbose_name='Дата')),
                ('Text', models.TextField(blank=True, verbose_name='Текст')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='Color',
            field=models.CharField(max_length=50, verbose_name='Цвет (html color code)'),
        ),
    ]
