# Generated by Django 3.2.10 on 2022-06-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='Color',
            field=models.CharField(default=0, max_length=50, verbose_name='Цвет (html color code)  #'),
            preserve_default=False,
        ),
    ]
