# Generated by Django 3.2.10 on 2022-06-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_tag_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=120)),
                ('product_id', models.CharField(max_length=120)),
                ('product_value', models.IntegerField()),
                ('product_size', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Корзина (system)',
                'verbose_name_plural': 'Корзина (system)',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=50, verbose_name='ФИО')),
                ('Phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('Email', models.CharField(max_length=50, verbose_name='Email')),
                ('Products', models.TextField(verbose_name='Заказ')),
                ('Delivery_type', models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], max_length=50, verbose_name='Тип доставки')),
                ('Payment_type', models.CharField(choices=[('При получении', 'При получении'), ('Онлайн', 'Онлайн')], max_length=50, verbose_name='Тип оплаты')),
                ('Payment_status', models.CharField(choices=[('Не оплачено', 'Не оплачено'), ('Оплачено', 'Оплачено')], default='Не оплачено', max_length=50, verbose_name='Статус оплаты')),
                ('Price', models.IntegerField(verbose_name='Итоговая цена')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
