# Generated by Django 3.2.10 on 2022-06-23 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_basket_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(blank=True, null=True, upload_to='banner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPEG', 'GIF', 'PNG', 'APNG', 'SVG', 'BMP', 'ICO'])], verbose_name='Изображение')),
                ('Link', models.CharField(blank=True, max_length=50, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннер',
            },
        ),
    ]
