# Generated by Django 3.2.10 on 2022-06-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='Video',
            new_name='Image',
        ),
    ]
