# Generated by Django 3.2.10 on 2022-07-08 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_rename_video_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='thanks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPEG', 'JPG', 'GIF', 'PNG', 'APNG', 'SVG', 'BMP', 'ICO'])], verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Yookassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=120)),
                ('Name_Sender', models.CharField(max_length=50, verbose_name='ФИО')),
                ('Phone_Sender', models.CharField(max_length=50, verbose_name='Телефон')),
                ('Email_Sender', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('Delivery_type', models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка'), ('Доставка вне города', 'Доставка вне города')], max_length=50, verbose_name='Тип доставки')),
                ('Name_Receiver', models.CharField(max_length=50, verbose_name='ФИО')),
                ('Phone_Receiver', models.CharField(max_length=50, verbose_name='Телефон')),
                ('Address', models.CharField(max_length=50, verbose_name='Адрес доставки')),
                ('Date', models.DateField(blank=True, default=None, verbose_name='Дата')),
                ('Time', models.TimeField(blank=True, default=None, verbose_name='Время')),
                ('Comment', models.TextField(verbose_name='Комментарий')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='Payment_type',
        ),
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.CharField(default=123, max_length=50, verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Comment',
            field=models.TextField(default=123, verbose_name='Комментарий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Date',
            field=models.DateField(blank=True, default=None, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='order',
            name='Time',
            field=models.TimeField(blank=True, default=None, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='banner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPEG', 'JPG', 'GIF', 'PNG', 'APNG', 'SVG', 'BMP', 'ICO'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Delivery_type',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], max_length=50, verbose_name='Способ получения'),
        ),
    ]
