# Generated by Django 3.2.10 on 2022-07-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20220708_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yookassa',
            name='Date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='yookassa',
            name='Time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Время'),
        ),
    ]
