# Generated by Django 4.0.6 on 2022-07-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20220709_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Имя')),
                ('Phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('Email', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('Message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.AlterModelOptions(
            name='thanks',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='FIO',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Phone',
        ),
        migrations.AddField(
            model_name='order',
            name='Email_Sender',
            field=models.CharField(blank=True, max_length=50, verbose_name='Email отправителя'),
        ),
        migrations.AddField(
            model_name='order',
            name='Name_Receiver',
            field=models.CharField(default=0, max_length=50, verbose_name='Имя получателя '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Name_Sender',
            field=models.CharField(default=0, max_length=50, verbose_name='Имя отправителя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Phone_Receiver',
            field=models.CharField(default=0, max_length=50, verbose_name='Телефон получателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Phone_Sender',
            field=models.CharField(default=0, max_length=50, verbose_name='Телефон отправителя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Delivery_type',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка'), ('Доставка вне города', 'Доставка вне города')], max_length=50, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Время'),
        ),
    ]
